import { useState, type FormEvent } from 'react';
import { Link, Navigate, useParams } from 'react-router-dom';
import { SCHOOLS } from '../data/schools';
import { PageShell } from '../components/layout/PageShell/PageShell';
import { Card } from '../components/shared/Card/Card';
import { Button } from '../components/shared/Button/Button';
import typography from '../styles/typography.module.css';

interface ChatMessage {
  role: 'user' | 'assistant';
  content: string;
}

export function SchoolAssistantPage() {
  const { schoolId } = useParams<{ schoolId: string }>();
  const school = SCHOOLS.find((s) => s.id === schoolId);

  const [messages, setMessages] = useState<ChatMessage[]>([]);
  const [input, setInput] = useState('');
  const [loading, setLoading] = useState(false);
  const [error, setError] = useState<string | null>(null);

  if (!school) {
    return <Navigate to="/schools" replace />;
  }

  async function handleSubmit(e: FormEvent) {
    e.preventDefault();
    const question = input.trim();
    if (!question || loading) return;

    const nextMessages: ChatMessage[] = [...messages, { role: 'user', content: question }];
    setMessages(nextMessages);
    setInput('');
    setError(null);
    setLoading(true);

    try {
      const res = await fetch('/api/chat', {
        method: 'POST',
        headers: { 'content-type': 'application/json' },
        body: JSON.stringify({ schoolId: school!.id, messages: nextMessages }),
      });
      const data = await res.json();
      if (!res.ok) {
        throw new Error(data.error || 'Something went wrong.');
      }
      setMessages([...nextMessages, { role: 'assistant', content: data.reply }]);
    } catch (err) {
      setError(err instanceof Error ? err.message : 'Something went wrong.');
    } finally {
      setLoading(false);
    }
  }

  return (
    <PageShell>
      <div>
        <Link to="/schools" className={typography.bodySmall} style={{ color: 'var(--color-text-muted)' }}>
          ← Schools
        </Link>
        <h1 className={typography.headingL} style={{ marginTop: 16 }}>
          {school.name}
        </h1>
        <p className={typography.bodyRegular} style={{ color: 'var(--color-text-muted)', marginTop: 4 }}>
          AI Assistant
        </p>
      </div>

      <Card>
        <p className={typography.label} style={{ color: 'var(--color-text-muted)' }}>
          GROUNDED IN OFFICIAL INFORMATION ONLY
        </p>
        <p className={typography.bodySmall} style={{ color: 'var(--color-text-muted)', marginTop: 8 }}>
          Answers are generated by Claude, restricted to this school's official mission, history, and
          admissions profile. It will say so if something isn't covered, rather than guessing.
        </p>
      </Card>

      <div style={{ display: 'flex', flexDirection: 'column', gap: 12 }}>
        {messages.length === 0 && (
          <p className={typography.bodySmall} style={{ color: 'var(--color-text-muted)' }}>
            Ask about {school.name}'s mission, history, curriculum, or admissions philosophy.
          </p>
        )}
        {messages.map((m, i) =>
          m.role === 'user' ? (
            <div key={i} style={{ display: 'flex', justifyContent: 'flex-end' }}>
              <div
                style={{
                  maxWidth: '80%',
                  background: 'var(--color-base-dark)',
                  color: 'var(--color-surface-bg)',
                  borderRadius: 12,
                  padding: 12,
                }}
              >
                <p className={typography.bodyRegular}>{m.content}</p>
              </div>
            </div>
          ) : (
            <Card key={i}>
              <p className={typography.bodyRegular}>{m.content}</p>
            </Card>
          ),
        )}
        {loading && (
          <Card>
            <p className={typography.bodySmall} style={{ color: 'var(--color-text-muted)' }}>
              Thinking…
            </p>
          </Card>
        )}
        {error && (
          <Card flagged>
            <p className={typography.bodySmall} style={{ color: 'var(--color-accent)' }}>
              {error}
            </p>
          </Card>
        )}
      </div>

      <form onSubmit={handleSubmit} style={{ display: 'flex', gap: 10 }}>
        <input
          type="text"
          value={input}
          onChange={(e) => setInput(e.target.value)}
          placeholder="Ask a question about this school…"
          className={typography.bodyRegular}
          style={{
            flex: 1,
            padding: '14px 16px',
            borderRadius: 24,
            border: '1px solid var(--color-text-muted)',
            background: 'transparent',
            color: 'var(--color-base-dark)',
          }}
        />
        <Button type="submit" disabled={loading || !input.trim()} style={{ width: 'auto', padding: '0 24px' }}>
          →
        </Button>
      </form>
    </PageShell>
  );
}
